# $Id: debug.py,v 1.7 2004/11/10 01:13:11 jpwarren Exp $
# $Revision: 1.7 $
#
#    BEEPy - A Python BEEP Library
#    Copyright (c) 2002-2004 Justin Warren <daedalus@eigenmagic.com>
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

'''

This is lame! There are at least 3 different ways this code base does logging,
I'm redirecting debug.log back to twisted.

"""
Customised debugging code.

@version: $Revision: 1.7 $
@author: Justin Warren
"""

import logging
import os
import sys

class MyLogger(logging.Logger):
    """
    MyLogger is a customised logging class used to debug BEEPy.
    It logs to a file beepy-debug.log by default so that when
    people run the testsuite they don't see all the standard
    ERROR and WARNING type messages generated by the negative
    tests.
    """

    def __init__(self, name):
        pid = os.getpid()

        ## Check to see if we're using the twisted logger
        ## and don't log as verbosely if we are, since the twisted
        ## logger already spews an imperial bucketload of information.
        ## We prefer the metric system, but what can you do?
        ## Those crazy Americans!
        if sys.modules.has_key('twisted.python.log'):
#            FORMAT = "%(module)11s %(levelname)7s: %(name)s: %(message)s"
            FORMAT = "%(module)15s %(levelname)7s: %(message)s"
        else:
#            FORMAT = "%(asctime)s [" + str(pid) + "] %(levelname)8s: %(name)s: %(message)s"
            FORMAT = "%(asctime)s [" + str(pid) + "] %(module)15s %(levelname)7s: %(message)s"

        #level = logging.DEBUG
        level = logging.INFO
        logging.Logger.__init__(self, name, level)

#        handler = logging.StreamHandler()

        ## Open a file for debug logging, overwriting any
        ## previous logfile.
        handler = logging.FileHandler('beepy-debug.log', 'w')

        formatter = logging.Formatter(FORMAT)
        handler.setFormatter(formatter)
        self.addHandler(handler)
        return

logging.setLoggerClass(MyLogger)
log = logging.getLogger('default')
'''

import twisted.python

# This doesn't work... it causes:
#          File "./echoserver.py", line 26, in <module>
#            twisted.python.log.startLogging(sys.stdout)
#          File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 397, in startLogging
#            startLoggingWithObserver(flo.emit, *a, **kw)
#          File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 412, in startLoggingWithObserver
#            msg("Log opened.")
#          File "/usr/lib/python2.5/site-packages/twisted/python/log.py", line 231, in msg
#            o = self.observers.pop(i)
#        exceptions.IndexError: pop index out of range
import sys
#twisted.python.log.startLogging(sys.stdout)

class Log:
	def debug(self, fmt, *msg):
		twisted.python.log.msg("dbg: " + fmt % msg)
	def warning(self, fmt, *msg):
		twisted.python.log.msg("wrn: " + fmt % msg)
	def error(self, fmt, *msg):
		twisted.python.log.err("err: " + fmt % msg)
	def info(self, fmt, *msg):
		twisted.python.log.err("inf: " + fmt % msg)
	
log = Log()

